name: ts_gcn
channels:
  - defaults
  - rdkit
  - schrodinger
  - conda-forge
dependencies:
  - h5py
  - hyperopt>=0.2.2
  - ipython
  - jupyter
  - matplotlib>=3.2
  - numpy>=1.18.0
  - openbabel
  - pandas>=1.1
  - pip>=19.0
  - psutil
  - py3dmol>=0.8.0
  - pymol
  - pyyaml
  - rdkit==2020.09.1.0
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - xlrd
  - xlwt
